{
 "title": "Kube1",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Local Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "klv_start_time / 1000000 / 60" }
   ]
  },
  { "title": "Node Name", "type": "stat", "gridPos": { "h": 4, "w": 2, "x": 0, "y": 3 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "Kube1 Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{image=\"kleverapp/klever-go:latest\",name=\"kube1\"}"
    }
   ]
  },
  { "title": "Node Version", "type": "stat", "gridPos": { "h": 4, "w": 3, "x": 5, "y": 3 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "Slots / Epcoh  -  Seconds / Block",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_slots_per_epoch{name=\"kube1\"}",
     "legendFormat": "Slots/Epoch"
    },
    {
     "expr": "klv_slot_duration{name=\"kube1\"} / 1000",
     "legendFormat": "Seconds/Block"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_epoch_number{name=\"kube1\"}",
     "legendFormat": "Current Epoch"
    }
   ]
  },
  {
   "title": "Epoch Slots / Minutes Remaining",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_slot_at_epoch_start + klv_slots_per_epoch - klv_current_slot{name=\"kube1\"}",
     "legendFormat": "Slots"
    },
    {
     "expr": "(klv_slot_at_epoch_start{name=\"kube1\"} + klv_slots_per_epoch{name=\"kube1\"} - klv_current_slot{name=\"kube1\"}) * 4 / 60",
     "legendFormat": "Minutes"
    }
   ]
  },
  { "title": "Node Version", "type": "stat", "gridPos": { "h": 4, "w": 3, "x": 16, "y": 3 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "Kube1 Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{image=\"kleverapp/klever-go:latest\",name=\"kube2\"}"
    }
   ]
  },
  { "title": "Node Name", "type": "stat", "gridPos": { "h": 4, "w": 2, "x": 22, "y": 3 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "Node Rating %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TempRating{name=\"kube1\"}"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_peer_type{name=\"kube1\"}",
     "legendFormat": "Kube1"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_synchronized_slot{name=\"kube1\"}",
     "legendFormat": "Sync Status"
    }
   ]
  },
  {
   "title": "Node Rating %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TempRating{name=\"kube2\"}"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_peer_type{name=\"kube2\"}",
     "legendFormat": "Kube1"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_synchronized_slot{name=\"kube2\"}",
     "legendFormat": "Sync Status"
    }
   ]
  },
  {
   "title": "System Health",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(name) (irate(node_cpu_seconds_total{mode=\"idle\",name=\"kube1\"}[1m])) * 100)",
     "legendFormat": "CPU - K1"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",name=\"kube1\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",name=\"kube1\"})",
     "legendFormat": "Disk - K1"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{name=\"kube1\"} / (node_memory_MemTotal_bytes{name=\"kube1\"})))* 100",
     "legendFormat": "RAM - K1"
    },
    {
     "expr": "(1- (node_memory_SwapFree_bytes{name=\"kube1\"} / node_memory_SwapTotal_bytes{name=\"kube1\"})) * 100",
     "legendFormat": "SWAP - K1"
    },
    {
     "expr": "100 - (avg by(name) (irate(node_cpu_seconds_total{mode=\"idle\",name=\"kube2\"}[1m])) * 100)",
     "legendFormat": "CPU - K2"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",name=\"kube2\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",name=\"kube2\"})",
     "legendFormat": "Disk - K2"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{name=\"kube2\"} / (node_memory_MemTotal_bytes{name=\"kube2\"})))* 100",
     "legendFormat": "RAM - K2"
    },
    {
     "expr": "(1- (node_memory_SwapFree_bytes{name=\"kube2\"} / node_memory_SwapTotal_bytes{name=\"kube2\"})) * 100",
     "legendFormat": "SWAP - K2"
    }
   ]
  },
  {
   "title": "Node Details",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stake_maximal{name=\"kube1\"}",
     "legendFormat": "Max Node Stake"
    },
    {
     "expr": "stake_total{name=\"kube1\"}",
     "legendFormat": "Current Node Stake"
    },
    {
     "expr": "stake_maximal - stake_total{name=\"kube1\"}",
     "legendFormat": "Delegation Left"
    },
    {
     "expr": "stake_rewards{name=\"kube1\"}",
     "legendFormat": "Distributed Rewards"
    }
   ]
  },
  {
   "title": "Node Details",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stake_maximal{name=\"kube2\"}",
     "legendFormat": "Max Node Stake"
    },
    {
     "expr": "stake_total{name=\"kube2\"}",
     "legendFormat": "Current Node Stake"
    },
    {
     "expr": "stake_maximal - stake_total{name=\"kube2\"}",
     "legendFormat": "Delegation Left"
    },
    {
     "expr": "stake_rewards{name=\"kube2\"}",
     "legendFormat": "Distributed Rewards"
    }
   ]
  },
  {
   "title": "Total Validator Leader Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TotalNumLeaderSuccess{name=\"kube1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Produced Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TotalNumValidatorSuccess{name=\"kube1\"} + TotalNumLeaderSuccess{name=\"kube1\"}"
    }
   ]
  },
  {
   "title": "Total Missed Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TotalNumLeaderFailure{name=\"kube1\"}"
    }
   ]
  },
  {
   "title": "Complete Status of all Klever Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elected_nodes{name=\"kube1\"}",
     "legendFormat": "Elected"
    },
    {
     "expr": "eligible_nodes{name=\"kube1\"}",
     "legendFormat": "Eligible"
    },
    {
     "expr": "jailed_nodes{name=\"kube1\"}",
     "legendFormat": "Jailed"
    },
    {
     "expr": "waiting_nodes{name=\"kube1\"}",
     "legendFormat": "Waiting"
    },
    {
     "expr": "inactive_nodes{name=\"kube1\"}",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Total Validator Leader Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TotalNumLeaderSuccess{name=\"kube2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Produced Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TotalNumValidatorSuccess{name=\"kube2\"} + TotalNumLeaderSuccess{name=\"kube2\"}"
    }
   ]
  },
  {
   "title": "Total Missed Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TotalNumLeaderFailure{name=\"kube2\"}"
    }
   ]
  },
  {
   "title": "Synced Slots / Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_highest_final_nonce{name=\"kube1\"}",
     "legendFormat": "Block Height"
    },
    {
     "expr": "klv_probable_highest_nonce{name=\"kube1\"}",
     "legendFormat": "Node Height"
    },
    {
     "expr": "klv_synchronized_slot{name=\"kube1\"}",
     "legendFormat": "Node Slot"
    },
    {
     "expr": "klv_current_slot{name=\"kube1\"}",
     "legendFormat": "Current Slot"
    }
   ]
  },
  {
   "title": "Total Validator Ignored Signatures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TotalNumValidatorIgnoredSignatures{name=\"kube1\"}"
    }
   ]
  },
  {
   "title": "KLV Supply/Staked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MaxKLV{name=\"kube1\"}",
     "legendFormat": "Max Supply"
    },
    {
     "expr": "CircKLV{name=\"kube1\"}",
     "legendFormat": "Circulating Supply"
    },
    {
     "expr": "StakedKLV{name=\"kube1\"}",
     "legendFormat": "Staked"
    }
   ]
  },
  {
   "title": "Synced Slots / Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_highest_final_nonce{name=\"kube2\"}",
     "legendFormat": "Block Height"
    },
    {
     "expr": "klv_probable_highest_nonce{name=\"kube2\"}",
     "legendFormat": "Node Height"
    },
    {
     "expr": "klv_synchronized_slot{name=\"kube2\"}",
     "legendFormat": "Node Slot"
    },
    {
     "expr": "klv_current_slot{name=\"kube2\"}",
     "legendFormat": "Current Slot"
    }
   ]
  },
  {
   "title": "Total Validator Ignored Signatures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TotalNumValidatorIgnoredSignatures{name=\"kube2\"}"
    }
   ]
  },
  {
   "title": "Connected Nodes / Peers / Validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_connected_nodes{name=\"kube1\"}",
     "legendFormat": "Connected Nodes"
    },
    {
     "expr": "klv_num_connected_peers{name=\"kube1\"}",
     "legendFormat": "Connected Peers"
    },
    {
     "expr": "klv_live_validator_nodes{name=\"kube1\"}",
     "legendFormat": "Live Validators"
    },
    {
     "expr": "klv_num_validators{name=\"kube1\"}",
     "legendFormat": "Epoch Validators"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_peak_tps{name=\"kube1\"}",
     "legendFormat": "TX Peak"
    },
    {
     "expr": "klv_tx_pool_load{name=\"kube1\"}",
     "legendFormat": "TX Pool Load"
    },
    {
     "expr": "klv_num_transactions_processed_tps_benchmark{name=\"kube1\"}",
     "legendFormat": "TX Processed"
    }
   ]
  },
  {
   "title": "KFI Supply/Staked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MaxKFI{name=\"kube1\"}",
     "legendFormat": "Max Supply"
    },
    {
     "expr": "CircKFI{name=\"kube1\"}",
     "legendFormat": "Circulating Supply"
    },
    {
     "expr": "StakedKFI{name=\"kube1\"}",
     "legendFormat": "Staked KFI"
    }
   ]
  },
  {
   "title": "Connected Nodes / Peers / Validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_connected_nodes{name=\"kube2\"}",
     "legendFormat": "Connected Nodes"
    },
    {
     "expr": "klv_num_connected_peers{name=\"kube2\"}",
     "legendFormat": "Connected Peers"
    },
    {
     "expr": "klv_live_validator_nodes{name=\"kube2\"}",
     "legendFormat": "Live Validators"
    },
    {
     "expr": "klv_num_validators{name=\"kube2\"}",
     "legendFormat": "Epoch Validators"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_peak_tps{name=\"kube2\"}",
     "legendFormat": "TX Peak"
    },
    {
     "expr": "klv_tx_pool_load{name=\"kube2\"}",
     "legendFormat": "TX Pool Load"
    },
    {
     "expr": "klv_num_transactions_processed_tps_benchmark{name=\"kube2\"}",
     "legendFormat": "TX Processed"
    }
   ]
  },
  {
   "title": "Validator Signed / Accepted Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_count_consensus{name=\"kube1\"}",
     "legendFormat": "Validator Signed"
    },
    {
     "expr": "klv_count_consensus_accepted_blocks{name=\"kube1\"}",
     "legendFormat": "Validator Accepted"
    }
   ]
  },
  {
   "title": "Total Validator Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_count_leader{name=\"kube1\"}",
     "legendFormat": "Proposed Blocks"
    },
    {
     "expr": "klv_count_accepted_blocks{name=\"kube1\"}",
     "legendFormat": "Accepted Blocks"
    }
   ]
  },
  {
   "title": "Validator Signed / Accepted Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_count_consensus{name=\"kube2\"}",
     "legendFormat": "Validator Signed"
    },
    {
     "expr": "klv_count_consensus_accepted_blocks{name=\"kube2\"}",
     "legendFormat": "Validator Accepted"
    }
   ]
  },
  {
   "title": "Total Validator Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_count_leader{name=\"kube2\"}",
     "legendFormat": "Proposed Blocks"
    },
    {
     "expr": "klv_count_accepted_blocks{name=\"kube2\"}",
     "legendFormat": "Accepted Blocks"
    }
   ]
  },
  {
   "title": "Transaction Pool Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "klv_tx_pool_load{name=\"kube1\"}",
     "legendFormat": "Kube1"
    },
    {
     "expr": "klv_tx_pool_load{name=\"kube2\"}",
     "legendFormat": "Kube2"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "klv_mem_load_percent{name=\"kube1\"}",
     "legendFormat": "Kube1"
    },
    {
     "expr": "klv_mem_load_percent{name=\"kube2\"}",
     "legendFormat": "Kube2"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "klv_cpu_load_percent{name=\"kube1\"}",
     "legendFormat": "Kube1"
    },
    {
     "expr": "klv_cpu_load_percent{name=\"kube2\"}",
     "legendFormat": "Kube2"
    }
   ]
  },
  {
   "title": "Processor usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",name=\"kube1\"}[1m])) * 100)",
     "legendFormat": "Kube1"
    },
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",name=\"kube2\"}[1m])) * 100)",
     "legendFormat": "Kube2"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[1m])*8",
     "legendFormat": "{{alias}} {{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total[1m])*8",
     "legendFormat": "{{alias}} {{device}} transmit"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{name=\"kube1\"}[1m])",
     "legendFormat": "{{alias}} {{device}} read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{name=\"kube1\"}[1m])",
     "legendFormat": "{{alias}} {{device}} write"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{name=\"kube2\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{name=\"kube2\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}